all: BackEnd.class UserAccount.class Event.class

BackEnd.class: BackEnd.java
	javac BackEnd.java
UserAccount.class: UserAccount.java
	javac UserAccount.java
Event.class: Event.java
	javac Event.java
