all: BackEnd.class UserAccount.class Event.class Transaction.class Event_Holder.class

BackEnd.class: BackEnd.java
	javac BackEnd.java
UserAccount.class: UserAccount.java
	javac UserAccount.java
Transaction.class: Transaction.java
	javac Transaction.java
Event.class: Event.java
	javac Event.java
Event_Holder.class: Event_Holder.java
	javac Event_Holder.java
clean:
	rm *.class