all: BackEnd.class UserAccount.class Transaction.class

BackEnd.class: BackEnd.java
	javac BackEnd.java
UserAccount.class: UserAccount.java
	javac UserAccount.java
Transaction.class: Transaction.java
	javac Transaction.java
